CREATE TABLE [dbo].[Table]
(
	[USER_ID] VARCHAR(50) NOT NULL PRIMARY KEY, 
    [PASSWORD] VARCHAR(50) NOT NULL, 
    [ADHAR_ID] INT NOT NULL, 
    [RETINA'S_IMAGE] IMAGE NOT NULL, 
    [NAME] VARCHAR(50) NOT NULL
)
